### ISSUE TITLE
Please add on-screen controls for touch devices.

### ISSUE THREAD

**Issue by edo9k** [bfirsh/jsnes#111]
I believe most mobile phones and tablets could run this emulator right from the browser, so having on-screen controls would really help in that. 

There's a javascript framework that does something similar to that, it's called [Akihabara](http://www.kesiev.com/akihabara/).

**Comment by julsgud** [comment]
Please add! Great project ♥️

**Comment by Louis-Lesage** [comment]
I will be giving myself a try to add touch control on this project https://github.com/bfirsh/jsnes-web
I'll be doing a pull request when im done.
