### ISSUE TITLE
There is a ROM error when we load up any game. Help Please.

### ISSUE THREAD

**Issue by reidragz** [bfirsh/jsnes#129]

**Comment by bfirsh** [comment]
What is the exact error? Can you describe the exact steps you are taking?

**Comment by reidragz** [comment]
I went to the website. Then, I clicked on a game and it brought up a pop-up window. The pop-up window had the same text for each game that I clicked on. It stated, "**jsnes.org says:** Error loading ROM: Error." I tried on my friend's chromebook and the same pop-up window appeared.

**Comment by functionalStoic** [comment]
I received the same issue

**Comment by kustuschmb** [comment]
Same here.

**Comment by workhorsy** [comment]
Looks like the server it is downloading the ROM files from does not have CORS setup properly:

```
Failed to load https://d3cto2l652k3y0.cloudfront.net/Bubble%20Bobble%20(U).nes: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://jsnes.org' is therefore not allowed access.
```

I've never used cloudfront, but you can fix it by adding something like this to your HTTP headers:

```
Access-Control-Allow-Origin: https://jsnes.org
```

**Comment by bfirsh** [comment]
Oooops

**Comment by bfirsh** [comment]
Yeah I changed the domain and forgot about that. Sorry all!

**Comment by bfirsh** [comment]
Fixed!
