### ISSUE TITLE
save state

### ISSUE THREAD

**Issue by jancborchardt** [bfirsh/jsnes#16]
To be able to actually play the games properly rather than just fiddle around, the game state should be saved. Not sure if internal game save functions can be accessed or if it’s feasible to just always have the latest state changed. The [Gameboy Emulator](http://gamecenter.grantgalitz.org/) by Grant Galitz seems to do both.

It’s probably best to always automatically save in localStorage/IndexedDB so that people can return to their game. Maybe even use [remotestorage](http://remotestorage.io) so you can change browsers.

**Comment by omarduarte** [comment]
@bfirsh, I may be able to add this feature given a few hints on which parts of the code need to be changed. Any ideas?

**Comment by josephlewis42** [comment]
I've got this working over in my repo at https://github.com/josephlewis42/jsnes

**Comment by jancborchardt** [comment]
@josephlewis42 can you open a pull request then? :)

**Comment by josephlewis42** [comment]
No problem, just did it!

The save is localstorage though rather than remotestorage.

**Comment by MeteorKL** [comment]
@josephlewis42 
I found an error while testing the localstorage function.
below "apply" should be replaced by "call" since s is a json object.
> JSNES.Mappers[4].prototype.fromJSON = function(s) {
>     JSNES.Mappers[0].prototype.fromJSON.apply(this, s);
>     ...
> }

**Comment by bfirsh** [comment]
I've moved the web emulator to a different repository and created an issue for it. Thanks all for your input! https://github.com/bfirsh/jsnes-web/issues/18

**Comment by oknoorap** [comment]
how to save and load state? any snippet here?

**Comment by MeteorKL** [comment]
I have done this by localStorage, hope this helps you. @oknoorap 
save:
```js
try{
    var saveData = JSON.stringify(nes.toJSON());
    localStorage.setItem(romName, saveData);
}catch(oException){
    if(oException.name == 'QuotaExceededError'){
        console.log('localStorage out of memory');
        localStorage.clear();
        localStorage.setItem(calcMD5(rompath), saveData);
    }
}
```

load:
```js
var saveData = localStorage.getItem(romName);
if( saveData == null ) {
    console.log("nothing to load");
    return;
}
var decodedData = JSON.parse(saveData);
nes.fromJSON(decodedData);
```

**Comment by oknoorap** [comment]
I just did that but doesn't works with jsnes-web, load state doesn't overwrite existing canvas

**Comment by MeteorKL** [comment]
Maybe you forgot to run `nes.frame()` after load state.

Or perhaps bfirsh removed some related code from `jsnes` to `jsnes-web`.

Anyway, I successed to do this with the old versions of `jsnes`

**Comment by oknoorap** [comment]
okay, will try, I'll post again when succeed

**Comment by oknoorap** [comment]
@MeteorKL After state loaded, I don't think that save state write bytes correctly, this glitch should be a number (score when mario kill mushroom monster) 

![image](https://user-images.githubusercontent.com/247018/32483136-3590330a-c3cd-11e7-8825-13097185da29.png)

**Comment by MeteorKL** [comment]
I don't quite understand `this glitch should be a number (score when mario kill mushroom monster)`
Did you mean that score is not the same as the old one?

**Comment by oknoorap** [comment]
This glitch graphics
![image](https://user-images.githubusercontent.com/247018/32483372-5c510d38-c3ce-11e7-8306-40e779ba69a2.png)

should be a number (score)
![image](https://user-images.githubusercontent.com/247018/32483409-897e8772-c3ce-11e7-940d-be49d93a99ca.png)

**Comment by MeteorKL** [comment]
Did you mean that 
the first graphics: after load
the second graphics: before load

**Comment by oknoorap** [comment]
yep, after load state there was glitchy graphics in the game

**Comment by MeteorKL** [comment]
Maybe you can stop the frame interval brefore save state, and continue it after load.

I guess it is just because you still run the game after saving state.

**Comment by oknoorap** [comment]
I do this.stop() or

```
this.frameTimer.stop();
this.speakers.stop();
```

before save to local storage, it's still has glitch

**Comment by MeteorKL** [comment]
It seems that the second graphics happens after the first graphics. It is pretty confusing and I have no idea about this.
Maybe you can try another rom to see whether this happens again.

**Comment by oknoorap** [comment]
Pacman doesn't have any trouble with graphics, but after load state, sounds are muted... 😄

**Comment by oknoorap** [comment]
Mario 2 after load state 😄 

![image](https://user-images.githubusercontent.com/247018/32485655-c35ac188-c3d6-11e7-90b8-e1cb261a8dff.png)

**Comment by MeteorKL** [comment]
Interesting bug :)
Maybe there are some mistakes in transforming data in localStorage. 
You can compare the JSON string before saving state and after loading state 
by saving them to txt and using some tools like vimdiffer.

**Comment by oknoorap** [comment]
I've modify `nes.js` by encoding `romData` to base64 in toJSON function, and decodes back in fromJSON function, it should be the same data... and it's still buggy :-D

**Comment by oknoorap** [comment]
may be it's related with Tile or ppu issue? can you help me 😭  @MeteorKL, I want to submit PR but I'm to dumb to understand jsnes's code...

**Comment by MeteorKL** [comment]
I'm also on the way to understanding jsnes's code. 
Maybe you can show your code to me by your Github or sending mail to me.

**Comment by bfirsh** [comment]
This is probably because `toJSON` or `fromJSON` somewhere is missing some data...

**Comment by oknoorap** [comment]
@bfirsh personally as developer I want to submit PR but it's too complicated to me to read low level code like yours, I'm sorry I just support you here, good luck, hope this issue will be solved 😄

**Comment by oknoorap** [comment]
any news related to glitch issue?

**Comment by oknoorap** [comment]
@bfirsh is this issue still can't be fixed? :)

**Comment by bfirsh** [comment]
I don’t have the time to look at it at the moment, but others are very welcome to tackle it! The main issue tracking is here: https://github.com/bfirsh/jsnes-web/issues/18

**Comment by Skypow2012** [comment]
I want to save data by save the nes.cpu.mem.(So this game state can lower from 1.9MB to 187KB) but in this way. when I load the mem, the frame's background is before background. Is there any method can refresh the background? I try to save the nes.ppu.bgbuffer, nes.ppu.vramMem, do nes.ppu.updatePalettes(), but not work, mayby I have sth wrong. Can anyone help me?
@bfirsh 

> localStorage.mem = JSON.stringify(nes.cpu.mem); // save
> nes.cpu.mem = JSON.parse(localStorage.mem); // load


![35f3dd7e27e2713b629c8a1b44464e3](https://user-images.githubusercontent.com/18132118/99916452-36c7f700-2d45-11eb-90ac-a7853ca0b060.png)

**Comment by JoeMeeks** [comment]
@bfirsh, @Skypow2012, @oknoorap, @lazyxu, @josephlewis42, @jancborchardt I have fixed the load via `fromJSON` in my PR:
https://github.com/bfirsh/jsnes/pull/397
