### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pix' of undefined 

### ISSUE THREAD

**Issue by minimi** [bfirsh/jsnes#17]
Game: Darkwing Duck (U) and some others

Console output:
Uncaught TypeError: Cannot read property 'pix' of undefined ppu.js:1011
JSNES.PPU.renderBgScanline ppu.js:1011
JSNES.PPU.endScanline ppu.js:428
JSNES.frame nes.js:149
(anonymous function) nes.js:82

Ugly solve is add
`if(!t) break;`
after
`t = ptTile[baseTile+nameTable[this.curNt].getTileIndex(this.cntHT,this.cntVT)];`

**Comment by bfirsh** [comment]
fixed! https://github.com/bfirsh/jsnes/pull/50
