### ISSUE TITLE
这儿报错,怎么去使用node.js - fs ?????????????

### ISSUE THREAD

**Issue by 958877748** [bfirsh/jsnes#176]
const fs = require('fs');

**Comment by bfirsh** [comment]
Would you mind explaining your problem in english?

I tried using Google Translate. The translation mentions something about an error, but you haven't provided one.

**Comment by 958877748** [comment]
My name Guo Lei ,Help me, I don't understand,
How to use node on the Web front-end, Requert (' FS ') is wrong?
How to run the node module in the browser?
< Above translation from Microsoft translation>

**Comment by 958877748** [comment]
Look at this.[cid:image002.png@01D427EA.FE53EAD0]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

**Comment by bfirsh** [comment]
This is just the core of the emulator. It won’t run in a browser by itself. 

You are probably looking for this. :) 
https://github.com/bfirsh/jsnes-web

**Comment by 958877748** [comment]
That's him, Thank you, Ben

**Comment by 958877748** [comment]
I'm not quite sure about your development environment for this project.
我不太清楚你这个项目的开发环境

Detailed information about the development environment can you tell me?
开发环境的详细信息能告诉我吗?
