### ISSUE TITLE
About online emulator

### ISSUE THREAD

**Issue by sqs3211849** [bfirsh/jsnes#178]
Hi everybody,I am a new guy on javascript,I saw a online emulator and then have interesting on it.
The webpage is:http://www.dream-island.org/ol/play.htm
I want to make an online emulator like that,hope to get everyone's help and get some hint or guidance.Thank you very much.

**Comment by sqs3211849** [comment]
@

**Comment by sqs3211849** [comment]
@bfirsh Can it be implemented through jsnes?

**Comment by bfirsh** [comment]
Yes! Here is the web version of JSNES with instructions on how to build it: https://github.com/bfirsh/jsnes-web
