### ISSUE TITLE
About the LICENSE

### ISSUE THREAD

**Issue by KuoKongQingYun** [bfirsh/jsnes#228]
I noticed that this project is licensed with GPLv3 ,
but it cause me confusion.
I visited some pages about this confusion,such as:
https://stackoverflow.com/questions/1239470/restrictions-of-gpl-on-javascript-libraries
https://stackoverflow.com/questions/532187/gpl-javascript-and-online-gaming
http://greendrake.info/#nfy0

but none of them is from a professional lawyer,
so it still a confusion.

I have just some questions:
1. Do I have to open source my whole front-side pages which use this library? if so,do I have to require other websites that my website linked to 'GPLed'?
For example:
I have a Page A that uses this library to run NES game,and Page A has a link which redirect to another Page B.
Do I have to make Page B open source? 
Go a step further.If Page A has a link which redirect to Google.com ,do I have to require Google to make their websites 'GPLed' ? It seems impossible , so it means that I can't link any other website which is not mine?if so ,no 'GPL-compatible' website can link my website too.
2. Do I have to limit visitors of my website to using open-source browser?

Because the GPL is not for web projects originally ,so when the GPL was applied to web project,which makes many disputes.
Thank you for this project.

**Comment by bfirsh** [comment]
Unfortunately I am not really sure. I am pretty sure we are violating the GPL in all sorts of ways.

I had to license it as GPL due to the emulator I based it on being GPL. I am in contact with the original author so perhaps we could have a go at relicensing it to something more sensible.

**Comment by KuoKongQingYun** [comment]
@bfirsh If there is any progress,please let me know.
Thank you.

**Comment by bfirsh** [comment]
Updates will be here: https://github.com/bfirsh/jsnes/issues/231

Thanks for the report!
