### ISSUE TITLE
How could we relicense to more liberal license?

### ISSUE THREAD

**Issue by bfirsh** [bfirsh/jsnes#231]
I don't want to start a discussion about what license is best, but there do seem to be some practical problems with using GPL for JavaScript projects. See #228.

I originally picked GPL because the emulator I based it on was licensed under GPL, so I had to license my derivative under it too.

It might be sensible to relicense to a more liberal license. I think it'll involve these steps:

1. Ask Jamie Sanders, who originally wrote vNES, to see if that's okay.
2. Ask all the contributors to JSNES if that's okay.

My feeling is that all the contributors probably didn't even notice that it was GPL, and there will be a resounding "I don't care" response, but we should probably go through the motions of getting permission just out of respect for their contributions. (My gung-ho attitude is probably why I am not a lawyer.)

If anyone has any experience/advice about this, it would be appreciated!

**Comment by bfirsh** [comment]
Jamie is fine with it being relicensed. We now just need to do a blame across the source code to find who the significant contributors are.

**Comment by greigs** [comment]
Has there been any progress on this front?

**Comment by bfirsh** [comment]
@greigs no I've been very busy, sorry! Would this be useful for you?

**Comment by greigs** [comment]
Yes definitely. It would enable more creative projects to use it where they may already be using a less restrictive license. Like mine.. https://twitter.com/ThereminHero/status/1189721638419472384

**Comment by bfirsh** [comment]
Hello @workhorsy @allie @BenShelton @jancborchardt @isharacomix @yasaricli @slembcke @shicks @rcopera @pubby @nosrevi @minimi @matthewbauer @malignantz @kira1928 @ecin!

Hope you're all well & safe in this ridiculous time. You have all made contributions to this repository (thank you!!). I'm thinking of relicensing it under Apache 2, and I need your consent to do that.

Is that OK? If I don't hear from you by 28th April, I'll assume it's a yes and make the migration.

I realise that isn't ideal consent, but I figure most of you don't mind. If you do mind and see this after 28th April, I'll remove your contribution to the project.

**Comment by workhorsy** [comment]
I give you permission to relicense my code contributions to jsnes under the Apache License 2.0.

**Comment by kira1928** [comment]
I'm OK to change my code in jsnes to Apache License 2.0.

**Comment by pubby** [comment]
Sure

**Comment by nosrevi** [comment]
I'm okay with relicensing my contribution under the Apache License 2.0.

**Comment by shicks** [comment]
Honestly I didn't even notice the license, even when I forked it (!) - I was a little relieved to see I didn't violate anything.  So this is fine with me.

**Comment by minimi** [comment]
Hello! No problem for me with relicensing

**Comment by yasaricli** [comment]
Hello; 

no problem, you can re-license.

**Comment by slembcke** [comment]
You have my permission. (Though I just wrote a bit of example code, I don't really think you needed it.)

**Comment by BenShelton** [comment]
Permission granted.

**Comment by bfirsh** [comment]
Done! :tada:

**Comment by jancborchardt** [comment]
Late to the party but am fine with it being relicensed to Apache 2 as well. :)
