### ISSUE TITLE
use webassembly

### ISSUE THREAD

**Issue by guyaqi** [bfirsh/jsnes#261]
if refactored in wasm, will this project provide a better performance?

**Comment by circl-lastname** [comment]
It works tho

**Comment by bfirsh** [comment]
Webassembly is usually a compile target, not a thing you'd write the app in. It would actually be easier to implement – you'd just lift an off-the-shelf emulator and compile to WASM. And, people have done this: https://github.com/workhorsy/SaltyNES

JSNES existed before any of these systems existed. An implementation compiled to WASM might have better performance, but the beauty of JSNES is you can see the implementation in pure JavaScript and you don't have to compile to another language.

As @circl-lastname said, it does work, and maximum performance is not the goal. :)
