### ISSUE TITLE
Undefined backgrounds freeze execution

### ISSUE THREAD

**Issue by isharacomix** [bfirsh/jsnes#27]
When a game has enabled backgrounds, but has not initialized the background's name table in the PPU VRAM, I get a type error "t is not defined" pointing to this line of the code:

```
    // Fetch data:
        t = ptTile[baseTile+nameTable[this.curNt].getTileIndex(this.cntHT,this.cntVT)];
        tpix = t.pix; // <-- t is not defined
        att = nameTable[this.curNt].getAttrib(this.cntHT,this.cntVT);
        scantile[tile] = t;
        attrib[tile] = att;
```

While this doesn't lock up the browser, it prevents the game from advancing. Can be reproduced with this rom image - runs in Mednafen, not in JSNES: http://isharacomix.org/junk/jsnes_bugreport.nes

**Comment by 220807** [comment]
你这个问题最后解决了没有？
