### ISSUE TITLE
Many ROMs loaded but can't run

### ISSUE THREAD

**Issue by LynnShyu** [bfirsh/jsnes#289]
Hello, I want to load GunSight.nes that made by KONAMI, the game was loaded successfully, but can't run, it's just stay grey screen. Except this ROM, I also found Cuba Soldier as the same, hope you could find it out，thanks:-)

**Comment by HTV04** [comment]
Probably has a mapper that isn't supported by JSNES at this time.

**Comment by LynnShyu** [comment]
> Probably has a mapper that isn't supported by JSNES at this time.

OK, thanks, and I hope more mapper will be supported by JSNES!
