### ISSUE TITLE
Not supported by mobile browsers?

### ISSUE THREAD

**Issue by LynnShyu** [bfirsh/jsnes#290]
I put the example html into my server, on the pc chrome it could be loaded and run successfully, but on the mobile browser like safari or chrome, it can't be loaded, just black

**Comment by rowanaut20** [comment]
Over at https://github.com/htv04/htv04.github.io/ we are working on fixing it. Works on all browsers so far except for audio

**Comment by king2015** [comment]
I wrote a website, which can be well displayed on my mobile phone.
[yikm.net](https://www.yikm.net)

**Comment by LynnShyu** [comment]
I can load ROMs successfully, it's a problem on the path of my ROM file
