### ISSUE TITLE
Multiplayer support

### ISSUE THREAD

**Issue by micahbolen** [bfirsh/jsnes#32]
What about doing something with [RealtimeMultiplayerNodeJs](https://github.com/onedayitwillmake/RealtimeMultiplayerNodeJs)?

If it sounds like a good idea, I'm up for doing some/all of the work.

FYI: I've cross-posted a [similar issue](https://github.com/onedayitwillmake/RealtimeMultiplayerNodeJs/issues/9) just to get some more feedback.

**Comment by bfirsh** [comment]
https://github.com/olahol/melody-jsnes :)
