### ISSUE TITLE
NPM Publish

### ISSUE THREAD

**Issue by reggi** [bfirsh/jsnes#35]
I just found this project and tried to `npm install jsnes --save` and found that the package was never published to NPM, I didn't want anyone to grab it so I published it myself. I'd love to transfer the ownership over to you. Just let me know your NPM username. Since your using NPM for installing everyone should be using it to install for versioning benefits. Let me know!

https://www.npmjs.org/package/jsnes

**Comment by bfirsh** [comment]
:tada: https://www.npmjs.com/package/jsnes
