### ISSUE TITLE
One game per page without dropdown

### ISSUE THREAD

**Issue by valioba** [bfirsh/jsnes#61]
Hello.
How will look the code (index.html) if I want to load only one game, without dropdown select game. Just load the game with loading the page?

I want to put an game in my wordpress.

**Comment by MeteorKL** [comment]
@valioba 
You can find related code in [ui.js](https://github.com/bfirsh/jsnes/blob/master/source/ui.js)
In line 69, we know that it loads a rom when you select a game.
```
self.romSelect.change(function() {
    self.loadROM();
});
```

In line 187, we can see a function called `loadROM`, and we know that it gets the rom by ajax.

You can change 
`url: escape(self.romSelect.val())` 
into 
`url: "rom/the_nes_game_you_want_to_load.nes"` 

Also, you need to add `self.loadROM();` after Created UI
(for example, you can add it between line 183 and line 184)

**Comment by bfirsh** [comment]
What @MeteorKL said. :)

Thanks @MeteorKL !
