### ISSUE TITLE
can not load  rom of MapperType2

### ISSUE THREAD

**Issue by pengqin** [bfirsh/jsnes#62]
jsnes can not load rom of MapperType2 .

I saw the source of JavaNes ,  The code is different from Jsnes.
The code is below

```
public class MapperCNROM extends MapperDefault {

	public MapperCNROM() {
	}

	public void init(NES nes) {
		super.init(nes);
	}

	public void write(int i, short word0) {
		if (i < 32768)
			super.write(i, word0);
		else
			load8kVromBank(word0 * 2, 0);
	}
}
```

**Comment by bfirsh** [comment]
Which ROM are you trying to load?

**Comment by minimi** [comment]
Hello,
Pull requests with this mapper (CNROM Mapper[3]) was accepted 4 days. Seems the issue not actual at the moment ;)

**Comment by pengqin** [comment]
thank you
